In [2]:
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from xgboost import XGBRegressor
from sklearn.decomposition import PCA

In [27]:
df = pd.read_csv('datasets/dataset_p1.csv')
df

,URUT,R1301A,R1301B,R1301C,R1303A,R1303B,R1303C,R1305A,R1305B,R1305C,...,R1206B,R1207,R1208,R1209,R1210A,R1210B,R1210C,R1210D,R1210E,index_k
0,1,1,1,1,4,1,4,1,2,2,...,2,1,2,3,2,2,1,1,2,62.31
1,2,1,2,2,4,1,2,4,2,2,...,3,1,2,4,1,2,1,1,2,72.21
2,3,1,1,2,1,1,4,4,1,2,...,2,1,2,4,2,2,1,2,2,70.80
3,4,1,1,2,2,1,2,2,2,2,...,3,2,4,2,2,2,2,1,2,72.89
4,5,1,1,2,4,1,2,2,2,2,...,2,4,2,3,1,2,2,1,2,72.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74679,74680,1,1,3,1,1,1,1,1,1,...,2,1,3,4,1,1,1,1,1,64.53
74680,74681,1,1,3,1,1,1,1,1,1,...,2,1,3,4,1,1,1,1,1,72.00
74681,74682,1,1,2,1,1,1,1,1,1,...,2,1,2,4,1,1,1,1,1,61.60
74682,74683,1,1,3,1,1,1,1,1,1,...,2,1,3,1,1,2,1,1,2,61.48
74683,74684,1,1,3,1,1,1,1,1,1,...,2,1,2,3,2,1,1,1,2,60.01

# EDA

## Kolom String

In [29]:

kolom_string = df.select_dtypes(include='object').columns.tolist()
if kolom_string:
    print(f"Kolom dengan tipe data 'object': {kolom_string}")
else:
    print("Tidak ada kolom dengan tipe data 'object' ditemukan.")

Kolom dengan tipe data 'object': ['R702B', 'R1607B', 'R1608C', 'R1609C']

In [30]:
df[['R1607B', 'R1608C', 'R1609C', 'R702B']]

      R1607B R1608C R1609C R702B
0        NaN    NaN    NaN   NaN
1        NaN    NaN    NaN   NaN
2        NaN    NaN    NaN   NaN
3        NaN    NaN    NaN   NaN
4          D    NaN    NaN   NaN
...      ...    ...    ...   ...
74679    NaN      D    NaN   NaN
74680     BC      F    NaN   NaN
74681    NaN      D    NaN   NaN
74682      D      A    NaN   NaN
74683    NaN    NaN    NaN   NaN

[74684 rows x 4 columns]

In [31]:
data_bukan_nan = df[['R1607B', 'R1608C', 'R1609C', 'R702B']].dropna()
data_bukan_nan

      R1607B R1608C R1609C             R702B
280        X      A      A           Jantung
335        C      D      A          Diabetes
577        B      B      A        USUS BUNTU
586        C      A      A      Darah Tinggi
788        X      E      A          Diabetes
...      ...    ...    ...               ...
73625      C      A      A              Asma
73807      X      A      A      Asam lambung
73811      X     AF      A              Asma
74597     BX      A      C  Penyakit tahunan
74670      C      D      A   Paru-paru basah

[1605 rows x 4 columns]

## Info Data

In [32]:
kolom_numeric = df.drop(columns=['R1607B', 'R1608C', 'R1609C', 'R702B'])
kolom_numeric

,index_k,R501,R502,R503,R504A,R504B,R504C,R601A,R601B1,R602A1,...,R1611,R1612,R1613A,R1613B,R1613C,R1614,R1615,R1616,URUT,WEIGHT
0,62.31,2,2,1,1,1,1,2,3.0,NaN,...,1,4,2,NaN,2.0,2,4,1,1,210.870377
1,72.21,3,2,1,1,1,1,1,NaN,1.0,...,1,4,2,NaN,2.0,2,4,2,2,210.870377
2,70.80,3,2,1,1,1,1,2,1.0,NaN,...,2,3,2,NaN,2.0,2,4,2,3,210.870377
3,72.89,3,2,1,1,1,1,1,NaN,1.0,...,1,4,2,NaN,2.0,2,4,2,4,210.870377
4,72.34,5,2,1,1,2,2,1,NaN,1.0,...,1,4,2,NaN,1.0,2,4,2,5,210.870377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74679,64.53,9,2,2,1,2,2,1,NaN,14.0,...,2,1,1,2.0,NaN,1,4,1,74680,544.102112
74680,72.00,9,1,2,1,2,2,1,NaN,6.0,...,2,1,1,2.0,NaN,1,4,1,74681,544.102112
74681,61.60,9,2,2,1,1,1,1,NaN,14.0,...,2,1,1,2.0,NaN,1,4,1,74682,544.102112
74682,61.48,5,2,1,1,1,1,1,NaN,14.0,...,2,1,2,NaN,2.0,1,4,3,74683,544.102112
74683,60.01,9,2,2,2,2,2,1,NaN,14.0,...,2,1,1,2.0,NaN,1,4,1,74684,544.102112

In [33]:
kolom_numeric.describe()

,index_k,R501,R502,R503,R504A,R504B,R504C,R601A,R601B1,R602A1,...,R1611,R1612,R1613A,R1613B,R1613C,R1614,R1615,R1616,URUT,WEIGHT
count,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,21301.000000,53383.000000,...,74684.000000,74684.000000,74684.000000,22804.000000,47270.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000
mean,66.410889,4.006615,1.856288,1.537317,1.111831,1.933774,1.626105,1.285215,1.178583,5.439765,...,2.011421,3.070028,1.756387,1.884406,1.811064,1.772722,3.496840,1.503254,37342.500000,934.529876
std,6.940839,1.956597,0.350800,0.498609,0.393634,0.932984,0.903802,0.451520,0.560209,5.412735,...,1.032286,1.091356,0.554728,0.319744,0.659539,0.881138,0.872296,0.986134,21559.558089,903.367661
min,9.480000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,17.859985
25%,62.160000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,3.000000,1.000000,18671.750000,342.553009
50%,66.190000,4.000000,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,3.000000,...,2.000000,3.000000,2.000000,2.000000,2.000000,1.000000,4.000000,1.000000,37342.500000,624.806641
75%,70.500000,5.000000,2.000000,2.000000,1.000000,3.000000,2.000000,2.000000,1.000000,8.000000,...,2.000000,4.000000,2.000000,2.000000,2.000000,3.000000,4.000000,2.000000,56013.250000,1274.261597
max,100.000000,10.000000,2.000000,2.000000,4.000000,4.000000,4.000000,2.000000,3.000000,17.000000,...,4.000000,4.000000,3.000000,2.000000,3.000000,4.000000,4.000000,4.000000,74684.000000,14644.427734

# Prepocessing

Proses ini menangani data hilang karena sparse dan encoding data kategorical

## Total Mising Value

In [35]:
missing = df.isnull().sum()
print("\nJumlah Missing Values:")
missing[missing > 0]

Jumlah Missing Values:

R601B1     53383
R602A1     21301
R602A2     21301
R602B      21301
R603       21301
           ...
R1609B5    25207
R1609B6    25207
R1609C     48158
R1613B     51880
R1613C     27414
Length: 99, dtype: int64

## handling data kategorical

### kolom R1607B, R1608C, R1609C

In [1]:
def encodeData(df, column,  references):
    # Loop melalui setiap huruf dalam daftar referensi
    for i, letter in enumerate(references):
        # Nama kolom baru akan menjadi R1607B_Huruf (misal: R1607B_A, R1607B_B)
        # Menggunakan f-string untuk membuat nama kolom dinamis
        # Menggunakan underscore untuk keterbacaan
        column_name = f'{column}_{letter}'
        df[column_name] = df[column].apply(
            lambda x: 0 if pd.isna(x) else (1 if letter in str(x) else 0)
        )

In [37]:
# Referensi huruf
references = ['A', 'B', 'C', 'D', 'E', 'F', 'X']
references2 = ['A', 'B', 'C', 'D', 'E', 'F']

encodeData(df, 'R1607B', references)
encodeData(df, 'R1608C', references2)
encodeData(df, 'R1609C', references2)

In [38]:
df.loc[df['R1607A'].isin([4,5]), ['R1607B','R1607B_A', 'R1607B_B', 'R1607B_C', 'R1607B_D', 'R1607B_E', 'R1607B_F', 'R1607B_X']].head()

  R1607B  R1607B_A  R1607B_B  R1607B_C  R1607B_D  R1607B_E  R1607B_F  R1607B_X
4      D         0         0         0         1         0         0         0
5      B         0         1         0         0         0         0         0
6      C         0         0         1         0         0         0         0
7      D         0         0         0         1         0         0         0
8      D         0         0         0         1         0         0         0

In [39]:
df.loc[df['R1608A'] == 1, ['R1608C','R1608C_A', 'R1608C_B', 'R1608C_C', 'R1608C_D', 'R1608C_E', 'R1608C_F']].head()

   R1608C  R1608C_A  R1608C_B  R1608C_C  R1608C_D  R1608C_E  R1608C_F
9       A         1         0         0         0         0         0
10      E         0         0         0         0         1         0
12      E         0         0         0         0         1         0
13      E         0         0         0         0         1         0
15      E         0         0         0         0         1         0

In [40]:
df.loc[df['R1609B1'] == 1, ['R1609C','R1609C_A', 'R1609C_B', 'R1609C_C', 'R1609C_D', 'R1609C_E', 'R1609C_F']].head()

   R1609C  R1609C_A  R1609C_B  R1609C_C  R1609C_D  R1609C_E  R1609C_F
23      A         1         0         0         0         0         0
28     BF         0         1         0         0         0         1
50      A         1         0         0         0         0         0
70      A         1         0         0         0         0         0
71     AB         1         1         0         0         0         0

In [41]:
df[['R1607B', 'R1607B_A', 'R1607B_B', 'R1607B_C', 'R1607B_D', 'R1607B_E', 'R1607B_F', 'R1607B_X','R1608C','R1608C_A', 'R1608C_B', 'R1608C_C', 'R1608C_D', 'R1608C_E', 'R1608C_F', 'R1609C', 'R1609C_A', 'R1609C_B', 'R1609C_C', 'R1609C_D', 'R1609C_E', 'R1609C_F']].isnull().sum()[lambda x: x > 0]

R1607B    16669
R1608C    21659
R1609C    48158
dtype: int64

In [42]:
#  drop column yang tidak terpakai
df.drop(columns=['R1607B', 'R1608C', 'R1609C'], inplace=True)

### kolom R702B (data penyakit)

In [43]:
import pandas as pd

# Kategori penyakit yang sudah disiapkan
categories = {
    "Penyakit Jantung dan Pembuluh Darah": ["sering pingsan tiba-tiba","pembekakan pembuluh darah","penyumbatan pembuluh darah","tensi","darah rendah","drop darah","penyempitan pembuluh darah","tensi tinggi","kurtosis aorta", "jantung", "koroner", "hipertensi", "tekanan darah tinggi","darah tinggi", "aritmia", "gagal jantung","penyumbatan darah"],
    "Penyakit Neurodegeneratif": ["alzheimer", "amyotrophic lateral sclerosis", "dimensia", "huntington", "parkinson"],
    "Penyakit Sistem Pernafasan": ["paru","afses paru","paru-paru","rinitis","faringitis","meniere syndrome","ispa","radang nasofaring","osa","nafas pendek","alergi dingin","tb","infeksi hidung","alergi asap","radang tenggorokan","covid","saluran pernafasan","peradangan paru","alergi debu","penyempitan pernafasan","tbc","sinusitis","polip", "amandel","step","tipes","sesak","sinositis","sesak nafas","asma", "bronkitis", "pneumonia", "copd"],
    "Penyakit Metabolik": ["kekurangan kalium","anemia","kencing manis","lemak darah","diabetes", "diabetes melitus", "kolesterol", "asam urat", "gout", "hiperlipidemia","gula darah","gula"],
    "Penyakit Tulang, Otot, dan Sendi": ["bengkak otot","kaki","avn","hnp","luka di kaki","kaki  terluka","pincang","otot bahu","kaki terluka","kolagen","cacat kaki","radang otot kaki","osteoarthrotis","punggung","kaki mudah merasa lemas","kaki selalu terasa lemas","hernea","sendi","gangguan persendian","kelelahan otot", "di bagin kaki","kesulitan untuk berjalan", "cacat pincang", "osteoritis","radang sendi","lutut","pengapuran","pinggang", "tulang", "hernia","patah kaki","osteoporosis", "artritis", "skoliosis", "fibromyalgia", "rematik"],
    "Penyakit Kanker dan Tumor": ["pembengkakan payudara","leukimia","kangker payudara","kista","kanker", "melanoma", "tumor","kangker perut"],
    "Penyakit Sistem Pencernaan": ["bagian perut","perut bengkak ( ada genangan air dlm perut )","pencernaan","berak darah","muntah darah","gangguan pencernaan","infeksi saluran pencernaan","empedu","refluks gastroesofagus","usus turung","pencernaan usus","gangguan empedu","kram usus", "liver","susah buang air besar", "radang usus", "empedu mengandung lemak dan lumpur","alergi saluran pencernaan","infeksi usus","tifus","peti liver","kuning","ambeyen", "hati","asam lambung","lambung", "maag", "gastritis", "batu empedu", "hepatitis", "ibs","usus buntu","gangguan usus"],
    "Penyakit Mata": ["ablosio retina", "tuna netra", "mata","katarak", "glaukoma", "konjungtivitis", "degenerasi makula", "buta","rabun"],
    "Penyakit Ginjal dan Saluran Kemih": ["kencing tidak lancar","infeksi saluran kemih","radang kencing","penyempitan saluran ginjal","gangguan saluran kencing","kencing batu","kencing frostat","ginjal", "batu ginjal", "isk", "gagal ginjal", "nefritis","infeksi saluran kencing"],
    "Penyakit Sistem Saraf dan Kejiwaan": ["pencairan di otak","jiwa","meningitis","tremor","gangguan jiwa","bisu","kejang","saraf terjepit","tekanan jiwa","kepala", "migrain","insomnia", "encephalitis","susah tidur", "vertigo","saraf","penyempitan saraf","epilepsi", "skizofrenia", "stroke", "depresi","mental","lumpuh","kejiwaan"],
    "Lainnya": ["kurang kalsium", "theroid","tiroid","teroid","hiperteroid","kelenjar","gondok","gondog","komplikasi","malaria","prostat","tiroit","autoimun","infeksi kulit yg parah","ada miom di rahim","keguguran","kelainan fisik","telinga pokak","kurang pendengaran","kelenjar leher","kaki bengkak spt kaki gajah  hanya saja bukan  kaki gajah","radang payudara","kulit","trauma menyeluruh","endometriosis","beri-beri","endometriosis","benjolan di leher","benjolan dileher","batuk","endrometriosis","prostat","porstat","tahunan","sel darah putih","miom habis operasi 6 bulan yllu","exim","maaf kronis","eksim","demam panas","dalam","terahum","pengangkatan rahim","kehamilan abdomen","kusta basah","gatal-gatal yang tidak bisa sembuh","virus tokso dinyatakan oleh dokter bahaya jika kalau hamil","hidroteroit","bulanan tidak normal","miyoma","miyoum","mioma","hypertirod","alergi semen","alergi","takanan","kronis","typoid","miom","kelebihan hormon","tekanan","pengobatan 6 bulan","payudara","gatal gatal","tidak bisa jalan","tua tdk bs jalan","dikarenakan umur yg sudah tua"],
}

# Fungsi memuat peta kesalahan ketik (typo_map)
def load_typo_map(file_path):
    typo_map = {}
    with open(file_path, 'r') as file:
        for line in file:
            typo, correct = line.strip().split('|')
            typo_map[typo] = correct
    return typo_map

# Muat peta kesalahan ketik
typo_map = load_typo_map('datasets/typo_map.txt')

# Fungsi normalisasi teks dengan memperbaiki typo menggunakan typo_map
def normalize_text(text, typo_map):
    # Pertama, ganti typo berdasarkan typo_map
    text = text.lower()
    for typo, correct in typo_map.items():
        text = text.replace(typo, correct)
    
    # Lakukan normalisasi lainnya
    return text.replace(" dan ", ",").replace("&", ",").replace("/", ",").replace(".", " ").strip()

# Fungsi pemrosesan baris data untuk kategorisasi penyakit
def process_row(entry, typo_map, categories):
    normalized_entry = normalize_text(entry, typo_map)
    normalized_diseases = [disease.strip() for disease in normalized_entry.split(",")]

    
    # Pemetaan kategori untuk setiap penyakit
    result = {category: 0 for category in categories.keys()}  # Default 0 (tidak)
    result['normalize_R702B'] = normalized_entry
    for disease in normalized_diseases:
        for category, keywords in categories.items():
            if any(keyword in disease for keyword in keywords):
                result[category] = 1  # 1 (ya)
    
    return result

# Fungsi utama untuk memproses dan menambahkan hasil ke df_combined
def process_and_add_to_df(df_combined, typo_map, categories):
    results = []

    # Proses setiap baris pada df_combined berdasarkan 'R702A' == "1"
    for entry in df_combined.loc[df_combined['R702A'] == 1, 'R702B']:
        result = process_row(entry, typo_map, categories)
        results.append(result)

    # Buat DataFrame hasil
    df_results = pd.DataFrame(results)

    # Kolom yang akan ditambahkan ke df_combined adalah hasil kategori R702A1 hingga R702A11
    df_combined_results = df_combined.loc[df_combined['R702A'] == 1].copy()

    # Menambahkan hasil kategori ke df_combined_results
    df_combined_results = df_combined.loc[df_combined['R702A'] == 1].copy().reset_index(drop=True)
    df_results = df_results.drop(columns=["normalize_R702B"])
    df_results = df_results.reset_index(drop=True)
    for i, column in enumerate(df_results.columns):
        new_column_name = f"R702B_{i+1}"
        df_combined_results[new_column_name] = df_results[column]

    print(df_combined_results.isna().sum())
    # Menambahkan kolom R702B_1 hingga R702B_11 dengan nilai default 0 untuk baris lainnya
    for i in range(1, len(categories.keys()) + 1):
        column_name = f"R702B_{i}"
        if column_name not in df_combined.columns:
            df_combined[column_name] = 0

    # # Gabungkan kembali dengan data df_combined
    df_combined_others = df_combined[df_combined['R702A'] != 1].copy()
    df_combined_final = pd.concat([df_combined_others, df_combined_results], ignore_index=True)

    # Pastikan tidak ada NaN dengan menggantinya menjadi nilai default
    # df_combined_final.fillna(2, inplace=True)

    return df_combined_final



# Proses dan tambahkan ke df_combined
df = process_and_add_to_df(df, typo_map, categories)
print(df.shape)

index_k     0
R501        0
R502        0
R503        0
R504A       0
           ..
R702B_7     0
R702B_8     0
R702B_9     0
R702B_10    0
R702B_11    0
Length: 284, dtype: int64
(74684, 284)

In [44]:
df[['R702B', 'R702B_1', 'R702B_2', 'R702B_3', 'R702B_4', 'R702B_5', 'R702B_6', 'R702B_7', 'R702B_8', 'R702B_9', 'R702B_10', 'R702B_11']].describe()

,R702B_1,R702B_2,R702B_3,R702B_4,R702B_5,R702B_6,R702B_7,R702B_8,R702B_9,R702B_10,R702B_11
count,74684.000000,74684.0,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000
mean,0.024276,0.0,0.010538,0.022401,0.004084,0.001620,0.017514,0.000616,0.002008,0.006628,0.005302
std,0.153905,0.0,0.102112,0.147985,0.063775,0.040219,0.131177,0.024810,0.044771,0.081142,0.072624
min,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [45]:
missing_values = df[['R702B_1', 'R702B_2', 'R702B_3', 'R702B_4', 'R702B_5', 'R702B_6', 'R702B_7', 'R702B_8', 'R702B_9', 'R702B_10', 'R702B_11']].isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

Series([], dtype: int64)

In [46]:
# drop column yang tidak terpakai
df.drop(columns=['R702B'], inplace=True)

In [47]:
df.shape

(74684, 283)

In [48]:
(df['R702A'][df['R702A'] == 1].count()) / df.shape[0] * 100

8.337796582936104

## handling data kategorical nominal

isi semua nilai kosong karena sparse dengan nilai -1

### R601B1, R601B2 => Jika R601A = 1

R601B2 tidak perlu di perbaiki karena sudah dipakai untuk perhitungan target dan tidak di gunakan sebagai feature

In [49]:
print("Jumlah nilai NaN di R601B1:", df['R601B1'].isna().sum())

Jumlah nilai NaN di R601B1: 53383

In [50]:
#  Mengisi nilai kolom R601B1 jika R601A bernilai 4 (Berkerja)
df.loc[df['R601A'] == 1, ['R601B1']] = [4]

In [51]:
df[['R601A','R601B1']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R602A1,R602A2,R602B,R603,R604A,R604B,R604C,R604D,R604E,R604F,R604G,R605 => Jika R601A = 2

Jika R601A bernilai 2 (Tidak), "R602A1","R602A2","R602B","R603","R604A","R604B","R604C","R604D","R604E","R604F","R604G","R605" Tidak Ada Nilai-nya

R605 tidak perlu di perbaiki karena sudah dipakai untuk perhitungan target dan tidak di gunakan sebagai feature

Isi nilai "R602A1","R602A2","R602B","R603","R604A","R604B","R604C","R604D","R604E","R604F","R604G" dengan -1 (tidak berlaku karena kondisi)

In [52]:
df.loc[df['R601A'] == 2, ['R602A1','R602A2','R602B','R603','R604A','R604B','R604C','R604D','R604E','R604F','R604G']] = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]

In [53]:
df[['R602A1','R602A2','R602B','R603','R604A','R604B','R604C','R604D','R604E','R604F','R604G']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R609C => Jika R609B != 3

In [54]:
df.loc[df['R609B'] != 3, ['R609C']] = [-1]
df[['R609C']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R701B => Jika R701A = 1

R701B diisi dengan nilai 1, karena R701A 1 = tidak ada keluhan maka R701B 1 = tidak terganggu karena  [???]

In [55]:
df.loc[df['R701A'] == 1, ['R701B']] = [1]
df[['R701B']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R703A1, R703A2 => Jika R701A berkode 1 dan R702A berkode 2

R703A1 di isi 2, karena tidak pernah rawat inap karena tidak pernah sakit atau ada keluah [???]

R703A1 di isi 4, karena tidak pernah rawat jalan karena tidak pernah sakit atau ada keluah [???]

In [56]:
df[['R703A1','R703A2']].isnull().sum()[lambda x: x > 0]

R703A1    24978
R703A2    24978
dtype: int64

In [57]:
df.loc[(df['R701A']==1) & (df['R702A']==2), ['R701A', 'R702A', 'R703A1','R703A2']].shape

(24978, 4)

In [58]:
df.loc[(df['R701A']==1) & (df['R702A']==2), ['R703A1','R703A2','R703B']] = [2,4,-1]

In [59]:
df[['R703A1','R703A2']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R703B => Jika R701A berkode 2, 3, 4 atau R702A berkode 1, atau R703A1 = 2 dan R703A2 = 2

In [60]:
df[['R703B']].isnull().sum()[lambda x: x > 0]

R703B    16297
dtype: int64

In [61]:
df.loc[(df['R703A1'] == 1) | (df['R703A2'] == 3) , ['R703A1','R703A2','R703B']]

       R703A1  R703A2  R703B
26        2.0     3.0    NaN
28        1.0     4.0    NaN
30        1.0     3.0    NaN
32        2.0     3.0    NaN
50        2.0     3.0    NaN
...       ...     ...    ...
74678     2.0     3.0    NaN
74679     2.0     3.0    NaN
74681     1.0     3.0    NaN
74682     2.0     3.0    NaN
74683     1.0     3.0    NaN

[16295 rows x 3 columns]

In [62]:
df.loc[(df['R703A1'] == 1) | (df['R703A2'] == 3), ['R703B']] = [-1]

In [63]:
df.loc[df['R703B'].isnull(), ['R701A', 'R702A','R703A1', 'R703A2', 'R703B']]

       R701A  R702A  R703A1  R703A2  R703B
33183      3      2     2.0     4.0    NaN
66765      2      2     2.0     4.0    NaN

In [64]:
# isi 1 mising value pada R703B tersisa dengan nilai terbanyak
df['R703B'].fillna(df['R703B'].mode()[0], inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18300\2446782049.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['R703B'].fillna(df['R703B'].mode()[0], inplace=True)

In [65]:
df[['R703B']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R705B1, R705B2, R705B3, R705B4, R705B5, R705B6 => Jika R705A = 2

In [66]:
df.loc[df['R705A'] == 2, ['R705B1', 'R705B2', 'R705B3', 'R705B4', 'R705B5', 'R705B6']] = [-1,-1,-1,-1,-1,-1]

In [67]:
df[['R705B1', 'R705B2', 'R705B3', 'R705B4', 'R705B5', 'R705B6']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R902B1, R902B2, R902B3, R902B4, R902B5, R902C => Jika R902A = 00

In [68]:
df.loc[df['R902A'] == 00, ['R902B1', 'R902B2', 'R902B3', 'R902B4', 'R902B5', 'R902C']] = [-1,-1,-1,-1,-1,-1]

In [69]:
df[['R902B1', 'R902B2', 'R902B3', 'R902B4', 'R902B5', 'R902C']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R1601A, R1601B => Jika R1206A = 3

In [70]:
df[['R1601A','R1601B']].isnull().sum()[lambda x: x > 0]

R1601A    1067
R1601B    1067
dtype: int64

In [71]:
df[['R1601A','R1601B']].describe()

             R1601A        R1601B
count  73617.000000  73617.000000
mean       6.732793      5.146746
std        3.536346      3.945203
min        1.000000      0.000000
25%        4.000000      2.000000
50%        6.000000      5.000000
75%        8.000000      7.000000
max       50.000000     49.000000

In [72]:
df.loc[df['R1206A'] == 3, ['R1601A','R1601B']] = [0,0]

In [73]:
df[['R1601A','R1601B']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R1604B => Jika R1604A = 2

In [74]:
df[['R1604B']].isnull().sum()[lambda x: x > 0]

R1604B    13133
dtype: int64

In [75]:
df.loc[df['R1604A'] == 2, ['R1604B']] = [1]

In [76]:
df[['R1604B']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R1608B => Jika R1608A = 1

In [77]:
df[['R1608B']].isnull().sum()[lambda x: x > 0]

R1608B    53025
dtype: int64

In [78]:
df.loc[df['R1608A'] == 1, ['R1608B']] = [-1]

In [79]:
df[['R1608B']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R1609B1, R1609B2, R1609B3, R1609B4, R1609B5, R1609B6 => Jika R1609A = 2

In [80]:
df[['R1609A','R1609B1','R1609B2','R1609B3','R1609B4','R1609B5','R1609B6']].isnull().sum()[lambda x: x > 0]

R1609B1    25207
R1609B2    25207
R1609B3    25207
R1609B4    25207
R1609B5    25207
R1609B6    25207
dtype: int64

In [81]:
df.loc[df['R1609A'] == 2, ['R1609A','R1609B1','R1609B2','R1609B3','R1609B4','R1609B5','R1609B6']] = [-1,-1,-1,-1,-1,-1,-1]

In [82]:
df[['R1609A','R1609B1','R1609B2','R1609B3','R1609B4','R1609B5','R1609B6']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R1613B => Jika R1613A != 1

In [83]:
df[['R1613B']].isnull().sum()[lambda x: x > 0]

R1613B    51880
dtype: int64

In [84]:
df.loc[df['R1613A'].isin([2,3]), ['R1613B']] = [-1]

In [85]:
df[['R1613B']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

### R1613C => Jika R1613A != 2

In [86]:
df[['R1613C']].isnull().sum()[lambda x: x > 0]

R1613C    27414
dtype: int64

In [87]:
df.loc[df['R1613A'].isin([1,3]), ['R1613C']] = [-1]

In [88]:
df[['R1613C']].isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

## Sisa Missing Value

In [89]:
df['R1103BK2']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
74679   NaN
74680   NaN
74681   NaN
74682   NaN
74683   NaN
Name: R1103BK2, Length: 74684, dtype: float64

In [90]:
missing = df.isnull().sum()
print("\nJumlah Missing Values:")
print(missing[missing > 0])

Jumlah Missing Values:
R1103BK2    74499
R1103BK3    74653
R1103BK4    74493
R1103BK5    74478
R1103BK6    73415
R1103BK7    74230
R1103CK2    74499
R1103CK3    74653
R1103CK4    74493
R1103CK5    74478
R1103CK6    73415
R1103CK7    74230
R1103DK2    74655
R1103DK3    74681
R1103DK4    74656
R1103DK5    74668
R1103DK6    74608
R1103DK7    74653
R1103EK2    74499
R1103EK3    74653
R1103EK4    74493
R1103EK5    74478
R1103EK6    73415
R1103EK7    74230
R1103FK2    74499
R1103FK3    74653
R1103FK4    74493
R1103FK5    74478
R1103FK6    73415
R1103FK7    74230
R1103GK2    74499
R1103GK3    74653
R1103GK4    74493
R1103GK5    74478
R1103GK6    73415
R1103GK7    74230
R1103HK2    74499
R1103HK3    74653
R1103HK4    74493
R1103HK5    74478
R1103HK6    73415
R1103HK7    74230
R1103IK2    74499
R1103IK3    74653
R1103IK4    74493
R1103IK5    74478
R1103IK6    73415
R1103IK7    74230
R1103JK2    74546
R1103JK3    74656
R1103JK4    74516
R1103JK5    74606
R1103JK6    73537
R1103JK7    74292
dtype: int64

In [91]:
# missing values yang tersisa di drop kolumnya karena hampir 100% dari total data hilang
df.drop(columns=['R1103AK2','R1103BK2','R1103CK2','R1103DK2','R1103EK2','R1103FK2','R1103GK2','R1103HK2','R1103IK2','R1103JK2','R1103AK3','R1103BK3','R1103CK3','R1103DK3','R1103EK3','R1103FK3','R1103GK3','R1103HK3','R1103IK3','R1103JK3','R1103AK4','R1103BK4','R1103CK4','R1103DK4','R1103EK4','R1103FK4','R1103GK4','R1103HK4','R1103IK4','R1103JK4','R1103AK5','R1103BK5','R1103CK5','R1103DK5','R1103EK5','R1103FK5','R1103GK5','R1103HK5','R1103IK5','R1103JK5','R1103AK6','R1103BK6','R1103CK6','R1103DK6','R1103EK6','R1103FK6','R1103GK6','R1103HK6','R1103IK6','R1103JK6','R1103AK7','R1103BK7','R1103CK7','R1103DK7','R1103EK7','R1103FK7','R1103GK7','R1103HK7','R1103IK7','R1103JK7'], inplace=True)

In [92]:
missing = df.isnull().sum()
print("\nJumlah Missing Values:")
print(missing[missing > 0])

Jumlah Missing Values:
Series([], dtype: int64)

## Standarisasi nilai Biner

Standarisasi untuk nilai biner yang 1 = ya dan 2 = tidak, menjadi 0 = tidak

In [93]:
def get_columns_with_specific_values(df):
    valid_columns = []
    allowed_values = {1, 2, -1}

    for column in df.columns:
        unique_values = set(df[column].unique())
        if unique_values.issubset(allowed_values):
            valid_columns.append(column)
    return valid_columns

# Dapatkan kolom yang memenuhi kriteria
kolom_hasil = get_columns_with_specific_values(df)
print(f"Kolom yang hanya berisi nilai 1, 2, dan/atau -1 adalah: {kolom_hasil}")

Kolom yang hanya berisi nilai 1, 2, dan/atau -1 adalah: ['R502', 'R503', 'R601A', 'R602B', 'R604A', 'R604B', 'R604C', 'R604D', 'R604E', 'R604F', 'R604G', 'R608', 'R702A', 'R703A1', 'R705A', 'R705B1', 'R705B2', 'R705B3', 'R705B4', 'R705B5', 'R705B6', 'R902B1', 'R902B2', 'R902B3', 'R902B4', 'R902B5', 'R1101B1', 'R1101B2', 'R1101B3', 'R1210A', 'R1210B', 'R1210C', 'R1210D', 'R1210E', 'R1409B', 'R1604A', 'R1608A', 'R1609A', 'R1609B1', 'R1609B2', 'R1609B3', 'R1609B4', 'R1609B5', 'R1609B6', 'R1613B']

In [94]:
# df["R1101A1"].describe()
for kolom in df[["R1101A1","R1101A2", "R1101A3", "R1101A4", "R1101A5"]].columns:
    print(f"\nKolom: {kolom}")
    print(df[kolom].value_counts())
    print("---")

Kolom: R1101A1
R1101A1
2    64768
1     6959
9     2957
Name: count, dtype: int64
---

Kolom: R1101A2
R1101A2
2    65587
1     6153
9     2944
Name: count, dtype: int64
---

Kolom: R1101A3
R1101A3
2    66626
1     4887
9     3171
Name: count, dtype: int64
---

Kolom: R1101A4
R1101A4
2    70415
9     3131
1     1138
Name: count, dtype: int64
---

Kolom: R1101A5
R1101A5
2    67990
1     3669
9     3025
Name: count, dtype: int64
---

In [95]:
# Kolom yang ingin diproses
cols = ["R1101A1", "R1101A2", "R1101A3", "R1101A4", "R1101A5"]

# Fungsi untuk mengganti nilai 9 dengan modus pada tiap kolom
for col in cols:
    modus = df.loc[df[col] != 9, col].mode()[0]
    df[col] = df[col].replace(9, modus)

In [96]:
# df["R1101A1"].describe()
for kolom in df[["R1101A1","R1101A2", "R1101A3", "R1101A4", "R1101A5"]].columns:
    print(f"\nKolom: {kolom}")
    print(df[kolom].value_counts())
    print("---")

Kolom: R1101A1
R1101A1
2    67725
1     6959
Name: count, dtype: int64
---

Kolom: R1101A2
R1101A2
2    68531
1     6153
Name: count, dtype: int64
---

Kolom: R1101A3
R1101A3
2    69797
1     4887
Name: count, dtype: int64
---

Kolom: R1101A4
R1101A4
2    73546
1     1138
Name: count, dtype: int64
---

Kolom: R1101A5
R1101A5
2    71015
1     3669
Name: count, dtype: int64
---

In [97]:
# pada kolom dibawah nilai 2 diganti dengan 0
kolom_terdampak = [
  "R502", "R503", "R601A", "R602B", "R604A", "R604B", "R604C", "R604D", "R604E", "R604F", "R604G", "R608",
  "R702A", "R703A1", "R703A2", "R705A", "R705B1", "R705B2", "R705B3", "R705B4", "R705B5", "R705B6", "R902B1",
  "R902B2", "R902B3", "R902B4", "R902B5", "R1101A1","R1101A2", "R1101A3", "R1101A4", "R1101A5", "R1101B1",
  "R1101B2", "R1101B3", "R1210A", "R1210B", "R1210C", "R1210D", "R1210E", "R1409B", "R1604A", "R1608A","R1609A",
  "R1609B1", "R1609B2", "R1609B3", "R1609B4", "R1609B5", "R1609B6"
]
for kolom in kolom_terdampak:
    df[kolom] = df[kolom].replace(2, 0)

In [98]:
for col in kolom_terdampak:
    print(f"\nKolom: {col}")
    print(df[col].value_counts(dropna=False))

Kolom: R502
R502
0    63951
1    10733
Name: count, dtype: int64

Kolom: R503
R503
0    40129
1    34555
Name: count, dtype: int64

Kolom: R601A
R601A
1    53383
0    21301
Name: count, dtype: int64

Kolom: R602B
R602B
 0.0    38709
-1.0    21301
 1.0    14674
Name: count, dtype: int64

Kolom: R604A
R604A
 1.0    41777
-1.0    21301
 0.0    11606
Name: count, dtype: int64

Kolom: R604B
R604B
 1.0    40560
-1.0    21301
 0.0    12823
Name: count, dtype: int64

Kolom: R604C
R604C
 1.0    37056
-1.0    21301
 0.0    16327
Name: count, dtype: int64

Kolom: R604D
R604D
 1.0    48652
-1.0    21301
 0.0     4731
Name: count, dtype: int64

Kolom: R604E
R604E
 1.0    39119
-1.0    21301
 0.0    14264
Name: count, dtype: int64

Kolom: R604F
R604F
 1.0    35115
-1.0    21301
 0.0    18268
Name: count, dtype: int64

Kolom: R604G
R604G
 1.0    48986
-1.0    21301
 0.0     4397
Name: count, dtype: int64

Kolom: R608
R608
0    63688
1    10996
Name: count, dtype: int64

Kolom: R702A
R702A
0    68457
1     6227
Name: count, dtype: int64

Kolom: R703A1
R703A1
0.0    73066
1.0     1618
Name: count, dtype: int64

Kolom: R703A2
R703A2
4.0    58807
3.0    15877
Name: count, dtype: int64

Kolom: R705A
R705A
1    50471
0    24213
Name: count, dtype: int64

Kolom: R705B1
R705B1
 1.0    26936
-1.0    24213
 0.0    23535
Name: count, dtype: int64

Kolom: R705B2
R705B2
 1.0    32959
-1.0    24213
 0.0    17512
Name: count, dtype: int64

Kolom: R705B3
R705B3
 1.0    46209
-1.0    24213
 0.0     4262
Name: count, dtype: int64

Kolom: R705B4
R705B4
 0.0    26457
-1.0    24213
 1.0    24014
Name: count, dtype: int64

Kolom: R705B5
R705B5
 0.0    38163
-1.0    24213
 1.0    12308
Name: count, dtype: int64

Kolom: R705B6
R705B6
 0.0    47570
-1.0    24213
 1.0     2901
Name: count, dtype: int64

Kolom: R902B1
R902B1
 1.0    62236
 0.0    11817
-1.0      631
Name: count, dtype: int64

Kolom: R902B2
R902B2
 0.0    61040
 1.0    13013
-1.0      631
Name: count, dtype: int64

Kolom: R902B3
R902B3
 0.0    54149
 1.0    19904
-1.0      631
Name: count, dtype: int64

Kolom: R902B4
R902B4
 1.0    65830
 0.0     8223
-1.0      631
Name: count, dtype: int64

Kolom: R902B5
R902B5
 0.0    47561
 1.0    26492
-1.0      631
Name: count, dtype: int64

Kolom: R1101A1
R1101A1
0    67725
1     6959
Name: count, dtype: int64

Kolom: R1101A2
R1101A2
0    68531
1     6153
Name: count, dtype: int64

Kolom: R1101A3
R1101A3
0    69797
1     4887
Name: count, dtype: int64

Kolom: R1101A4
R1101A4
0    73546
1     1138
Name: count, dtype: int64

Kolom: R1101A5
R1101A5
0    71015
1     3669
Name: count, dtype: int64

Kolom: R1101B1
R1101B1
0    72665
1     2019
Name: count, dtype: int64

Kolom: R1101B2
R1101B2
0    68321
1     6363
Name: count, dtype: int64

Kolom: R1101B3
R1101B3
0    73388
1     1296
Name: count, dtype: int64

Kolom: R1210A
R1210A
1    59890
0    14794
Name: count, dtype: int64

Kolom: R1210B
R1210B
0    58746
1    15938
Name: count, dtype: int64

Kolom: R1210C
R1210C
1    59753
0    14931
Name: count, dtype: int64

Kolom: R1210D
R1210D
1    65773
0     8911
Name: count, dtype: int64

Kolom: R1210E
R1210E
0    42754
1    31930
Name: count, dtype: int64

Kolom: R1409B
R1409B
1    40961
0    33723
Name: count, dtype: int64

Kolom: R1604A
R1604A
1    61551
0    13133
Name: count, dtype: int64

Kolom: R1608A
R1608A
1    53025
0    21659
Name: count, dtype: int64

Kolom: R1609A
R1609A
 1    49477
-1    25207
Name: count, dtype: int64

Kolom: R1609B1
R1609B1
 0.0    27345
-1.0    25207
 1.0    22132
Name: count, dtype: int64

Kolom: R1609B2
R1609B2
 0.0    46382
-1.0    25207
 1.0     3095
Name: count, dtype: int64

Kolom: R1609B3
R1609B3
 0.0    43682
-1.0    25207
 1.0     5795
Name: count, dtype: int64

Kolom: R1609B4
R1609B4
 0.0    46128
-1.0    25207
 1.0     3349
Name: count, dtype: int64

Kolom: R1609B5
R1609B5
 0.0    41522
-1.0    25207
 1.0     7955
Name: count, dtype: int64

Kolom: R1609B6
R1609B6
 0.0    49240
-1.0    25207
 1.0      237
Name: count, dtype: int64

##

## Encoding

In [99]:
df.shape
df.to_csv('./datasets/dataset_clean4.csv', index=False)

In [ ]:
# Encoding kolom kategorikal nominal
kolom_kategorikal_nominal = [
    "R601B1", "R602A1", "R602A2", "R703B", "R902C", "R1201", "R1205", "R1608B", "R1613B"
]

kolom_kategorikal_ordinal = [
    "R501", "R504A", "R504B", "R504C", "R603", "R606", "R607", "R609A", "R609B", "R609C", "R701A", "R701B",
    "R704A", "R704B", "R704C", "R704D", "R704E", "R704F", "R704G", "R704H",
    "R706A", "R706B", "R706C", "R706D", "R706E", "R706F", "R706G", "R706H", "R706I", "R706J", "R707A", "R707B", "R707C",
    "R801A", "R801B", "R801C", "R801D", "R1001A", "R1001B", "R1001C", "R1101C", "R1104A", "R1104B", "R1104C", "R1105",
    "R1106A", "R1106B", "R1107A", "R1107B", "R1203", "R1204", "R1206A", "R1206B", "R1207", "R1208", "R1209",
    "R1301A", "R1301B", "R1301C", "R1303A", "R1303B", "R1303C", "R1305A", "R1305B", "R1305C", "R1305D",
    "R1401A", "R1401B", "R1401C", "R1401D", "R1403A", "R1403B", "R1403C", "R1405A", "R1405B", "R1405C",
    "R1407A", "R1407B", "R1409A", "R1411A", "R1411B", "R1411C", "R1602", "R1603", "R1604B",
    "R1605A", "R1605B", "R1605C", "R1605D", "R1605E", "R1606", "R1607A", "R1610", "R1611", "R1612",
    "R1613A", "R1613C", "R1614", "R1615", "R1616"
]

kolom_biner = [
    "R502", "R503", "R601A", "R602B", "R604A", "R604B", "R604C", "R604D", "R604E", "R604F", "R604G", "R608",
    "R702A", "R703A1", "R703A2", "R705A", "R705B1", "R705B2", "R705B3", "R705B4", "R705B5", "R705B6", "R902B1",
    "R902B2", "R902B3", "R902B4", "R902B5", "R1101A1", "R1101A2", "R1101A3", "R1101A4", "R1101A5", "R1101B1",
    "R1101B2", "R1101B3", "R1210A", "R1210B", "R1210C", "R1210D", "R1210E", "R1409B", "R1604A", "R1608A", "R1609A",
    "R1609B1", "R1609B2", "R1609B3", "R1609B4", "R1609B5", "R1609B6"
]

# sudah biner
kolom_kategorikal_encoded = [
    "R702B1", "R702B2", "R702B3", "R702B4", "R702B5", "R702B6", "R702B7", "R702B8", "R702B9", "R702B10", "R702B11",
    'R1607B', 'R1607B_A', 'R1607B_B', 'R1607B_C', 'R1607B_D', 'R1607B_E', 'R1607B_F', 'R1607B_X',
    'R1609C', 'R1609C_A', 'R1609C_B', 'R1609C_C', 'R1609C_D', 'R1609C_E', 'R1609C_F',
    'R1608C', 'R1608C_A', 'R1608C_B', 'R1608C_C', 'R1608C_D', 'R1608C_E', 'R1608C_F',
]

# nilai 1 - 10
kolomscoring = [
    "R1003A", "R1003B", "R1003C", "R1003D", "R1003E", "R1003F", "R1003G", "R1003H", "R1003I", "R1003J",
    "R1004A", "R1004B", "R1004C", "R1004D", "R1004E", "R1004F",
    "R1002A", "R1002B", "R1002C", "R1002D", "R1002E", "R1002F", "R1002G", "R1002H", "R1002I", "R1002J"
]

kolomnominal = [
    "R1601A",
    "R1601B",
    "R902A",
    "R1202",
    "R901"
]

r1103_biner = [
	'R1103AK2', 'R1103AK3', 'R1103AK4', 'R1103AK5', 'R1103AK6', 'R1103AK7', 
	'R1103CK2', 'R1103CK3', 'R1103CK4', 'R1103CK5', 'R1103CK6', 'R1103CK7', 
	'R1103EK2', 'R1103EK3', 'R1103EK4', 'R1103EK5', 'R1103EK6', 'R1103EK7', 
	'R1103HK2', 'R1103HK3', 'R1103HK4', 'R1103HK5', 'R1103HK6', 'R1103HK7', 
	'R1103IK2', 'R1103IK3', 'R1103IK4', 'R1103IK5', 'R1103IK6', 'R1103IK7'
]

r1103_katogorical = [
	'R1103BK2', 'R1103BK3', 'R1103BK4', 'R1103BK5', 'R1103BK6', 'R1103BK7', 
	'R1103DK2', 'R1103DK3', 'R1103DK4', 'R1103DK5', 'R1103DK6', 'R1103DK7', 
	'R1103FK2', 'R1103FK3', 'R1103FK4', 'R1103FK5', 'R1103FK6', 'R1103FK7', 
	'R1103GK2', 'R1103GK3', 'R1103GK4', 'R1103GK5', 'R1103GK6', 'R1103GK7', 
	'R1103JK2', 'R1103JK3', 'R1103JK4', 'R1103JK5', 'R1103JK6', 'R1103JK7'
]

In [101]:
df[kolomnominal].describe()

             R1601A        R1601B         R902A         R1202          R901
count  74684.000000  74684.000000  74684.000000  74684.000000  74684.000000
mean       6.636602      5.073215     26.467408     75.005784     46.581722
std        3.600758      3.964253     16.120430     52.559595     19.479345
min        0.000000      0.000000      0.000000      3.000000      0.000000
25%        4.000000      2.000000     14.000000     45.000000     35.000000
50%        6.000000      5.000000     21.000000     63.000000     46.000000
75%        8.000000      7.000000     35.000000     90.000000     56.000000
max       50.000000     49.000000     98.000000    998.000000     98.000000

In [102]:
# Gabungkan semua kolom yang diharapkan (nominal + ordinal)
kolom_diharapkan = set(kolom_kategorikal_nominal + kolom_kategorikal_ordinal + kolom_biner + kolom_kategorikal_encoded + kolomnominal + kolomscoring)
print("Jumlah kolom yang diharapkan:", len(kolom_diharapkan)) 
print("Jumlah kolom asal:", len(df.columns)) 
# Ambil kolom yang ada di df
kolom_df = set(df.columns)

# Cari kolom yang ada di df tetapi tidak ada dalam daftar kolom_kategorikal
kolom_tambahan = kolom_df - kolom_diharapkan

# Tampilkan kolom tersebut
print("Jumlah kolom dalam df yang tidak ada dalam daftar :", len(kolom_tambahan))
print("Kolom dalam df yang tidak ada dalam daftar kategorikal:")
print(kolom_tambahan)

Jumlah kolom yang diharapkan: 223
Jumlah kolom asal: 223
Jumlah kolom dalam df yang tidak ada dalam daftar : 14
Kolom dalam df yang tidak ada dalam daftar kategorikal:
{'R702B_2', 'R702B_4', 'WEIGHT', 'R702B_8', 'R702B_3', 'R702B_10', 'index_k', 'R702B_1', 'URUT', 'R702B_6', 'R702B_9', 'R702B_5', 'R702B_11', 'R702B_7'}

In [103]:
for col in df.columns:
    median_value = df.loc[df[col] != -1, col].median()
    df[col] = df[col].replace(-1, median_value)

In [104]:
# ColumnTransformer dengan OneHotEncoder
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot_nominal', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), kolom_kategorikal_nominal)
    ],
    remainder='passthrough'  # mempertahankan kolom lainnya tanpa perubahan
)
# Fit dan transform data
X_encoded = preprocessor.fit_transform(df)

# Ambil nama kolom hasil One-Hot Encoding
encoded_cols = preprocessor.named_transformers_['onehot_nominal'].get_feature_names_out(kolom_kategorikal_nominal)

# Ambil kolom yang bukan kategori
non_encoded_cols = [col for col in df.columns if col not in kolom_kategorikal_nominal]

# Buat DataFrame hasil encoding
df_encoded = pd.DataFrame(X_encoded, columns=list(encoded_cols) + non_encoded_cols)

# Tampilkan hasil
print(df_encoded.head())

   R601B1_1.0  R601B1_2.0  R601B1_3.0  R601B1_4.0  R602A1_1.0  R602A1_2.0  \
0         0.0         0.0         1.0         0.0         0.0         0.0
1         0.0         0.0         0.0         1.0         1.0         0.0
2         1.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         1.0         1.0         0.0
4         0.0         0.0         0.0         1.0         1.0         0.0

   R602A1_3.0  R602A1_4.0  R602A1_5.0  R602A1_6.0  ...  R702B_2  R702B_3  \
0         1.0         0.0         0.0         0.0  ...      0.0      0.0
1         0.0         0.0         0.0         0.0  ...      0.0      0.0
2         1.0         0.0         0.0         0.0  ...      0.0      0.0
3         0.0         0.0         0.0         0.0  ...      0.0      0.0
4         0.0         0.0         0.0         0.0  ...      0.0      0.0

   R702B_4  R702B_5  R702B_6  R702B_7  R702B_8  R702B_9  R702B_10  R702B_11
0      0.0      0.0      0.0      0.0      0.0      0.0       0.0       0.0
1      0.0      0.0      0.0      0.0      0.0      0.0       0.0       0.0
2      0.0      0.0      0.0      0.0      0.0      0.0       0.0       0.0
3      0.0      0.0      0.0      0.0      0.0      0.0       0.0       0.0
4      0.0      0.0      0.0      0.0      0.0      0.0       0.0       0.0

[5 rows x 267 columns]

In [105]:
df["R1003F"].describe()

count    74684.000000
mean         6.814806
std          2.025769
min          0.000000
25%          6.000000
50%          7.000000
75%          8.000000
max         10.000000
Name: R1003F, dtype: float64

In [106]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

# Ganti ini dengan path ke file dataset kamu
# df = pd.read_csv("data.csv")
# Contoh dummy:
# df = pd.DataFrame(np.random.randn(100, 220), columns=[f'F{i}' for i in range(220)])

# Inisialisasi PDF untuk menyimpan semua plot
with PdfPages('outlier_plots_kolomnominal.pdf') as pdf:
    for col in kolomnominal:
        if pd.api.types.is_numeric_dtype(df[col]):
            plt.figure(figsize=(8, 4))
            sns.boxplot(x=df[col])
            plt.title(f'Outlier Detection - {col}')
            plt.tight_layout()
            pdf.savefig()  # Simpan plot ke file PDF
            plt.close()

print("Selesai. File PDF dengan semua plot boxplot outlier telah dibuat sebagai 'outlier_plots.pdf'")

Selesai. File PDF dengan semua plot boxplot outlier telah dibuat sebagai 'outlier_plots.pdf'

In [107]:

print(df["R503"].value_counts(dropna=False))

R503
0    40129
1    34555
Name: count, dtype: int64

## ...

# Modeling and Feature Importance

In [ ]:
df_encoded.describe()

,R601B1_1.0,R601B1_2.0,R601B1_3.0,R601B1_4.0,R602A1_1.0,R602A1_2.0,R602A1_3.0,R602A1_4.0,R602A1_5.0,R602A1_6.0,...,R702B2,R702B3,R702B4,R702B5,R702B6,R702B7,R702B8,R702B9,R702B10,R702B11
count,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,...,74684.0,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000,74684.000000
mean,0.258114,0.003267,0.023834,0.714785,0.331959,0.010042,0.340006,0.001794,0.002584,0.026284,...,0.0,0.010538,0.022401,0.004084,0.001620,0.017514,0.000616,0.002008,0.006628,0.005302
std,0.437600,0.057065,0.152532,0.451520,0.470919,0.099708,0.473714,0.042321,0.050770,0.159980,...,0.0,0.102112,0.147985,0.063775,0.040219,0.131177,0.024810,0.044771,0.081142,0.072624
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# Fitur dan target
y = df_encoded['index_k']
sample_weight = df_encoded['WEIGHT']
sample_weight = sample_weight / np.mean(sample_weight)
X = df_encoded.drop(columns=['index_k', 'WEIGHT', "R702B1", "R702B2", "R702B3", "R702B4", "R702B5", "R702B6", "R702B7", "R702B8", "R702B9", "R702B10", "R702B11"])

In [ ]:
X

,R601B1_1.0,R601B1_2.0,R601B1_3.0,R601B1_4.0,R602A1_1.0,R602A1_2.0,R602A1_3.0,R602A1_4.0,R602A1_5.0,R602A1_6.0,...,R1608C_C,R1608C_D,R1608C_E,R1608C_F,R1609C_A,R1609C_B,R1609C_C,R1609C_D,R1609C_E,R1609C_F
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74679,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74680,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74681,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
74682,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74683,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Random Forest

In [ ]:
rf_X_train, rf_X_test, rf_y_train, rf_y_test, weight_train, weight_test = train_test_split(
    X, y, sample_weight, test_size=0.3, random_state=42
)

In [ ]:
rfr = RandomForestRegressor(n_estimators=100, random_state=42, max_depth=10, min_samples_leaf=5)
rfr.fit(rf_X_train, rf_y_train, sample_weight=weight_train)

RandomForestRegressor(max_depth=10, min_samples_leaf=5, random_state=42)

In [ ]:
# --- 4. Prediksi pada Data Testing ---
rf_y_pred = rfr.predict(rf_X_test)

# --- 5. Evaluasi Model ---
mse = mean_squared_error(rf_y_test, rf_y_pred)
rmse = np.sqrt(mse) # Root Mean Squared Error
r2 = r2_score(rf_y_test, rf_y_pred)

print(f"\nMetrik Evaluasi Model:")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Metrik Evaluasi Model:
Mean Squared Error (MSE): 30.45
Root Mean Squared Error (RMSE): 5.52
R-squared (R2): 0.37

In [ ]:
feature_importances = rfr.feature_importances_
feature_names = X.columns
# Pastikan feature_names sesuai dengan jumlah fitur di X
if len(feature_names) != len(feature_importances):
    # Jika Anda memiliki data riil, pastikan kolom X_train memiliki nama kolom
    # Atau gunakan indeks fitur sebagai nama sementara
    feature_names_display = [f'fitur_{i}' for i in range(len(feature_importances))]
else:
    feature_names_display = feature_names

importance_df = pd.DataFrame({'Feature': feature_names_display, 'Importance': feature_importances})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

print("\n--- 50 Fitur Teratas Berdasarkan Importansi ---")
print(importance_df.head(50).to_string(index=False)) # .to_string(index=False) untuk membersihkan output

--- 50 Fitur Teratas Berdasarkan Importansi ---
Feature  Importance
 R1003F    0.202196
 R1002C    0.048169
 R1002A    0.039730
 R1003D    0.035237
 R1003G    0.034624
 R1003H    0.025639
 R1002E    0.023697
   R501    0.022022
 R1003A    0.021210
 R1003C    0.020589
 R1002F    0.019181
 R1002D    0.017784
  R609A    0.017359
 R1409B    0.016553
 R1002J    0.014857
 R1003I    0.014183
   URUT    0.014068
 R1004C    0.013103
 R1004B    0.013095
  R609B    0.012729
 R1003J    0.012571
 R1004F    0.012215
   R606    0.011771
 R1002B    0.011317
 R1003B    0.011045
 R1003E    0.009812
  R1202    0.009541
 R1605E    0.009066
  R902A    0.009057
 R1002I    0.008799
   R901    0.007081
 R1405C    0.005872
 R1004A    0.005777
  R504C    0.005639
 R1004E    0.005623
 R1004D    0.005118
   R603    0.005048
 R1303A    0.005009
 R1002H    0.004765
 R1605A    0.004375
 R1002G    0.004322
  R1208    0.004103
 R1601A    0.003928
 R1605D    0.003704
 R1601B    0.003668
  R1603    0.003448
  R609C    0.003414
 R1001C    0.003161
 R1305D    0.003109
 R1001B    0.003071

In [ ]:
mostImportanceFeature = importance_df.head(50)['Feature'].tolist()
# mostImportanceFeature
nrf_X_train, nrf_X_test, nrf_y_train, nrf_y_test, weight_train, weight_test = train_test_split(
    X[mostImportanceFeature], y, sample_weight, test_size=0.3, random_state=42
)

In [ ]:
X[mostImportanceFeature].shape

(74684, 50)

In [ ]:
nrfr = RandomForestRegressor(n_estimators=100, random_state=42, max_depth=10, min_samples_leaf=5)
nrfr.fit(nrf_X_train, nrf_y_train, sample_weight=weight_train)

RandomForestRegressor(max_depth=10, min_samples_leaf=5, random_state=42)

In [ ]:
# --- 4. Prediksi pada Data Testing ---
nrf_y_pred = nrfr.predict(nrf_X_test)

# --- 5. Evaluasi Model ---
nrf_mse = mean_squared_error(nrf_y_test, nrf_y_pred)
nrf_rmse = np.sqrt(nrf_mse) # Root Mean Squared Error
nrf_r2 = r2_score(nrf_y_test, nrf_y_pred)

print(f"\nMetrik Evaluasi Model:")
print(f"Mean Squared Error (nrf_MSE): {nrf_mse:.2f}")
print(f"Root Mean Squared Error (nrf_RMSE): {nrf_rmse:.2f}")
print(f"R-squared (R2): {nrf_r2:.2f}")

Metrik Evaluasi Model:
Mean Squared Error (nrf_MSE): 30.52
Root Mean Squared Error (nrf_RMSE): 5.52
R-squared (R2): 0.37

## XGB

In [ ]:
xgb_X_train, xgb_X_test, xgb_y_train, xgb_y_test, weight_train, weight_test = train_test_split(
    X, y, sample_weight, test_size=0.3, random_state=42
)

In [ ]:
# 3. Buat model XGBoost Regressor
xgb = XGBRegressor( random_state=42)
# 4. Latih model
xgb.fit(xgb_X_train, xgb_y_train)
# 5. Prediksi
xgb_y_pred = xgb.predict(xgb_X_test)
# 6. Evaluasi model
mse = mean_squared_error(xgb_y_test, xgb_y_pred)
r2 = r2_score(xgb_y_test, xgb_y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Mean Squared Error (MSE): 27.34
R-squared (R2): 0.43

In [ ]:
xgb_feature_importances = xgb.feature_importances_
xgb_feature_names = xgb_X_train.columns

# Buat DataFrame dan ambil 50 fitur teratas
xgb_importance_df = pd.DataFrame({
    'Feature': xgb_feature_names,
    'Importance': xgb_feature_importances
}).sort_values(by='Importance', ascending=False)

xgb_mostImportanceFeature = xgb_importance_df.head(50)['Feature'].tolist()

In [ ]:
nxgb_X_train, nxgb_X_test, nxgb_y_train, nxgb_y_test, weight_train, weight_test = train_test_split(
    X[xgb_mostImportanceFeature], y, sample_weight, test_size=0.3, random_state=42
)

In [ ]:
# 3. Buat model XGBoost Regressor
nxgb = XGBRegressor( random_state=42)
# 4. Latih model
nxgb.fit(nxgb_X_train, nxgb_y_train)
# 5. Prediksi
nxgb_y_pred = nxgb.predict(nxgb_X_test)
# 6. Evaluasi model
mse = mean_squared_error(nxgb_y_test, nxgb_y_pred)
r2 = r2_score(nxgb_y_test, nxgb_y_pred)
rmse = np.sqrt(mse)

print(f"\nMetrik Evaluasi Model:")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Metrik Evaluasi Model:
Root Mean Squared Error (RMSE): 5.41
Mean Squared Error (MSE): 29.29
R-squared (R2): 0.39

# PCA

In [ ]:
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)

In [ ]:
print(f"Jumlah komponen utama: {pca.n_components_}")
print("Rasio variansi yang dijelaskan oleh tiap komponen:")
print(pca.explained_variance_ratio_)

Jumlah komponen utama: 1
Rasio variansi yang dijelaskan oleh tiap komponen:
[0.99999226]

In [ ]:
import numpy as np
import pandas as pd

# Ambil komponen dan nama fitur
components = pca.components_  # shape: (n_components, n_features)
feature_names = X.columns     # nama-nama fitur asli

# Ambil 5 fitur teratas (dengan kontribusi terbesar) per komponen
top_features_per_component = {}

for i, component in enumerate(components):
    component_number = f'PC{i+1}'
    
    # Ambil indeks fitur dengan kontribusi absolut tertinggi
    top_indices = np.abs(component).argsort()[::-1][:15]
    
    # Buat DataFrame mini untuk komponen ini
    top_features = [(feature_names[j], component[j]) for j in top_indices]
    
    # Simpan ke dictionary
    top_features_per_component[component_number] = top_features

# Tampilkan hasil
for pc, features in top_features_per_component.items():
    print(f"\n{pc} paling dipengaruhi oleh:")
    for fname, weight in features:
        print(f"  {fname:<30} kontribusi: {weight:.4f}")

PC1 paling dipengaruhi oleh:
  URUT                           kontribusi: 1.0000
  R1202                          kontribusi: -0.0001
  R901                           kontribusi: -0.0000
  R1601A                         kontribusi: -0.0000
  R1601B                         kontribusi: -0.0000
  R1206B                         kontribusi: 0.0000
  R1002J                         kontribusi: 0.0000
  R1001C                         kontribusi: -0.0000
  R902A                          kontribusi: 0.0000
  R1004A                         kontribusi: 0.0000
  R1002I                         kontribusi: 0.0000
  R1607A                         kontribusi: -0.0000
  R1004D                         kontribusi: -0.0000
  R1004B                         kontribusi: -0.0000
  R1002H                         kontribusi: 0.0000

In [ ]:
# 2. Split train-test
pca_X_train, pca_X_test, pca_y_train, pca_y_test, weight_train, weight_test = train_test_split(X_pca , y, sample_weight, test_size=0.2, random_state=42)

In [ ]:
# 3. Buat model XGBoost Regressor
pca_xgb = XGBRegressor( random_state=42)
# 4. Latih model
pca_xgb.fit(xgb_X_train, xgb_y_train)
# 5. Prediksi
pca_xgb_y_pred = pca_xgb.predict(xgb_X_test)
# 6. Evaluasi model
mse = mean_squared_error(xgb_y_test, pca_xgb_y_pred)
r2 = r2_score(xgb_y_test, xgb_y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Mean Squared Error (MSE): 27.34
R-squared (R2): 0.43

# LASSO REGRESSION

In [109]:
from sklearn.linear_model import LassoCV
lasso = LassoCV(cv=5)
lasso.fit(X, y)
selected_features = X.columns[(lasso.coef_ != 0)]
X_lasso = X[selected_features]

NameError: name 'X' is not defined

In [ ]:
# 2. Split train-test
lasso_X_train, lasso_X_test, lasso_y_train, lasso_y_test, weight_train, weight_test = train_test_split(X_lasso , y, sample_weight, test_size=0.2, random_state=42)

In [ ]:
# 3. Buat model XGboost Regressor
lasso_xgb = XGBRegressor( random_state=42)
# 4. Latih model
lasso_xgb.fit(lasso_X_train, lasso_y_train)
# 5. Prediksi
lasso_xgb_y_pred = lasso_xgb.predict(lasso_X_test)
# 6. Evaluasi model
mse = mean_squared_error(lasso_y_test, lasso_xgb_y_pred)
r2 = r2_score(lasso_y_test, lasso_xgb_y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Mean Squared Error (MSE): 44.65
R-squared (R2): 0.09

# Recursive Feature Elimination (RFE)

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

model = LinearRegression()
rfe = RFE(estimator=model, n_features_to_select=50)
VX_rfe = rfe.fit_transform(X, y)
selected_columns = X.columns[rfe.support_]

In [ ]:
X_rfe = X[selected_columns]
# 2. Split train-test
rfe_X_train, rfe_X_test, rfe_y_train, rfe_y_test, weight_train, weight_test = train_test_split(X_rfe , y, sample_weight, test_size=0.2, random_state=42)

In [ ]:
# 3. Buat model XGBoost Regressor
rfe_xgb = XGBRegressor( random_state=42)
# 4. Latih model
rfe_xgb.fit(rfe_X_train, rfe_y_train)
# 5. Prediksi
rfe_xgb_y_pred = rfe_xgb.predict(rfe_X_test)
# 6. Evaluasi model
mse = mean_squared_error(rfe_y_test, rfe_xgb_y_pred)
r2 = r2_score(rfe_y_test, rfe_xgb_y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Mean Squared Error (MSE): 46.84
R-squared (R2): 0.05

In [ ]:
from sklearn.linear_model import HuberRegressor
from sklearn.datasets import make_regression
import numpy as np

# Generate synthetic data with outliers
# X, y = make_regression(n_samples=100, n_features=1, noise=10)
# y[::10] += 100  # Add outliers

# Fitur dan target
y = df_encoded['index_k']
sample_weight = df_encoded['WEIGHT']
sample_weight = sample_weight / np.mean(sample_weight)
X = df_encoded.drop(columns=['index_k', 'WEIGHT', "R702B1", "R702B2", "R702B3", "R702B4", "R702B5", "R702B6", "R702B7", "R702B8", "R702B9", "R702B10", "R702B11"])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=10)
X_pca = pca.fit_transform(X)

# 2. Split train-test
X_train, X_test, y_train, y_test, weight_train, weight_test = train_test_split(X_pca , y, sample_weight, test_size=0.2, random_state=42)

# rf_X_train, rf_X_test, rf_y_train, rf_y_test, weight_train, weight_test = train_test_split(
#     X, y, sample_weight, test_size=0.3, random_state=42
# )


# Fit Huber Regressor
huber = HuberRegressor().fit(X_train, y_train, sample_weight=weight_train)

# Coefficient and intercept
print("Intercept:", huber.intercept_)
print("Coef:", huber.coef_)

Intercept: 51.86088460147078
Coef: [-1.81183768e-04  2.40754295e-02 -8.00167312e-02  2.33915739e-02
 -1.70346375e+00  1.45073521e-01  1.23772595e+00  3.83287993e+00
  2.89452599e+00  7.79855674e+00]

c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_huber.py:342: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

In [ ]:
explained_var = pca.explained_variance_ratio_.cumsum()
print("Cumulative explained variance:", explained_var)

Cumulative explained variance: [0.99999226 0.99999821 0.99999907 0.99999959 0.99999964 0.99999968
 0.99999972 0.99999974 0.99999976 0.99999977]

In [ ]:
y_pred = huber.predict(X_test)

# 5. Evaluasi
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# 6. Print hasil
print(f"R-squared (R²): {r2:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

R-squared (R²): -18.1270
Mean Absolute Error (MAE): 23.5097
Mean Squared Error (MSE): 938.2530
Root Mean Squared Error (RMSE): 30.6309